### ISSUE TITLE
The instructions are wrong

### ISSUE THREAD

**Issue by flammie** [apertium/apertium-init#38]
I tried apertium-init out:
```
$ apertium-init/apertium-init.py tlh-swe --analyser1=hfst
Successfully created /home/tpirinen/github/apertium/apertium-tlh-swe.
Initialized git repository apertium-tlh-swe.
Successfully added and committed files to git repository apertium-tlh-swe.
To push your new local repository to incubator in the Apertium organisation on GitHub:
	apertium-init.py -pe /home/tpirinen/github/apertium/apertium-tlh-swe
$ apertium-init/apertium-init.py -pe apertium-tlh-swe/
usage: apertium-init.py [-h] [-d DESTINATION] [-p]
                        [-pe PUSH_EXISTING_TO_GITHUB] [-u USERNAME]
                        [-a {lt,lttoolbox,hfst}] [-a1 {lt,lttoolbox,hfst}]
                        [-a2 {lt,lttoolbox,hfst}] [--no-rlx1] [--no-rlx2]
                        [--no-prob1] [--no-prob2] [--no-pgen1] [--no-pgen2]
                        name
apertium-init.py: error: the following arguments are required: name
```
I also cannot execute `git push -u origin master` or so in the dir:
```
$ git push -u origin master
fatal: 'origin' does not appear to be a git repository
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
```

**Comment by sushain97** [comment]
> I also cannot execute git push -u origin master or so in the dir:

Yes, it doesn't add the remote until you actually specify `-pe` or `-p`, the same behavior as if initialized the Git repo yourself (and I would not want it to).

**Comment by flammie** [comment]
-pe doesn't work.

See:
```
$ apertium-init/apertium-init.py -pe apertium-tlh-swe/
usage: apertium-init.py [-h] [-d DESTINATION] [-p]
                        [-pe PUSH_EXISTING_TO_GITHUB] [-u USERNAME]
                        [-a {lt,lttoolbox,hfst}] [-a1 {lt,lttoolbox,hfst}]
                        [-a2 {lt,lttoolbox,hfst}] [--no-rlx1] [--no-rlx2]
                        [--no-prob1] [--no-prob2] [--no-pgen1] [--no-pgen2]
                        name
apertium-init.py: error: the following arguments are required: name
```

**Comment by sushain97** [comment]
No, you're using it wrong :)

See the new instructions.

**Comment by flammie** [comment]
ah, I missed the change :-)

Now I face another problem:
```
$ apertium-init/apertium-init.py -pe apertium-tlh-swe/ tlh-swe
GitHub Password (tommi.antero.pirinen@uni-hamburg.de): 
Authentication failed. Retrying...
GitHub Password (tommi.antero.pirinen@uni-hamburg.de): 
Authentication failed. Retrying...
GitHub Password (tommi.antero.pirinen@uni-hamburg.de): 
Authentication failed. Retrying...
GitHub Password (tommi.antero.pirinen@uni-hamburg.de): 
Authentication failed. Retrying...
GitHub Password (tommi.antero.pirinen@uni-hamburg.de): Traceback (most recent call last):
  File "apertium-init/apertium-init.py", line 168, in create_github_repository
    response = urllib.request.urlopen(req)
  File "/usr/lib64/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib64/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apertium-init/apertium-init.py", line 168, in create_github_repository
    response = urllib.request.urlopen(req)
  File "/usr/lib64/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib64/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apertium-init/apertium-init.py", line 168, in create_github_repository
    response = urllib.request.urlopen(req)
  File "/usr/lib64/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib64/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apertium-init/apertium-init.py", line 168, in create_github_repository
    response = urllib.request.urlopen(req)
  File "/usr/lib64/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib64/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apertium-init/apertium-init.py", line 271, in <module>
    main()
  File "apertium-init/apertium-init.py", line 230, in main
    push_to_github(args, args.destination, username)
  File "apertium-init/apertium-init.py", line 179, in push_to_github
    response = create_github_repository()
  File "apertium-init/apertium-init.py", line 174, in create_github_repository
    return create_github_repository()
  File "apertium-init/apertium-init.py", line 174, in create_github_repository
    return create_github_repository()
  File "apertium-init/apertium-init.py", line 174, in create_github_repository
    return create_github_repository()
  File "apertium-init/apertium-init.py", line 174, in create_github_repository
    return create_github_repository()
  File "apertium-init/apertium-init.py", line 158, in create_github_repository
    password = getpass.getpass(prompt='GitHub Password ({}): '.format(username))
  File "/usr/lib64/python3.5/getpass.py", line 77, in unix_getpass
    passwd = _raw_input(prompt, stream, input=input)
  File "/usr/lib64/python3.5/getpass.py", line 146, in _raw_input
    line = input.readline()
KeyboardInterrupt
```
I think user.email from global config isn't good for github, I either need an option to override (other systems aks to specify user name after first failure) or it could just use github.user from git config, I don't know why but it seems I have this setup globally:

```
$ git config -l
user.name=Tommi A Pirinen
user.email=tommi.antero.pirinen@uni-hamburg.de
user.signingkey=0xB55C73B38C4B9642!
github.user=flammie
core.editor=vim
merge.tool=vimdiff
color.ui=auto
http.postbuffer=242880000
```

**Comment by sushain97** [comment]
See --username.

**Comment by sushain97** [comment]
It should work but I don't think it's been tested rigorously.

**Comment by sushain97** [comment]
Feel free to open a feature request for using github.user. It would be ideal. I don't know if everyone has it set though.

**Comment by flammie** [comment]
Ähm, it seems it gives authentication failed in all cases, maybe it's about insufficient rights or something. If it had worked it would be a good thing to document in the readme, I think most users would be needing it.

**Comment by sushain97** [comment]
> it would be a good thing to document in the readme

Indeed, #29 is for that.
