### ISSUE TITLE
apertium-init hangs waiting for input

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-init#45]
```
fran@matxine:/tmp$ python3 ~/scripts/apertium-init.py --help
^CTraceback (most recent call last):
  File "/home/fran/scripts/apertium-init.py", line 18, in <module>
    import subprocess
  File "/usr/lib/python3.6/subprocess.py", line 50, in <module>
    import signal
  File "/home/fran/scripts/signal.py", line 4, in <module>
    doc = sys.stdin.read()
KeyboardInterrupt
```

What is the XML that it expects to read from stdin ?

```
$ echo "" | python3 ~/scripts/apertium-init.py --help
Traceback (most recent call last):
  File "/home/fran/scripts/apertium-init.py", line 18, in <module>
    import subprocess
  File "/usr/lib/python3.6/subprocess.py", line 50, in <module>
    import signal
  File "/home/fran/scripts/signal.py", line 6, in <module>
    root = ET.fromstring(doc)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1315, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 2, column 0
```

**Comment by sushain97** [comment]
This isn't apertium-init's problem. You have a script named signal in the path that is overwriting Python standard modules. That will break tons of things.

**Comment by ftyers** [comment]
How can we get `apertium-init` to not try and load random stuff in the directory it is run from ?

**Comment by sushain97** [comment]
That's not apertium-init. It's the Python subprocess module which requires the signal module. You'd have to some real path garbage to fix this natively and I'm not certain it's possible.

**Comment by sushain97** [comment]
(and it might break the script on other platforms depending on the location/method of installation)

**Comment by ftyers** [comment]
A solution would be to just run the script in a different directory?

**Comment by sushain97** [comment]
Yep. Or rename the signal script ;) pip install apertium-init would also work and then it's easily upgradeable without having to redownload.
